version: "3.7"

networks:
    default:
        name: golang-learning
        external: true
  
services:
  golang:
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=alex
      - DB_PASSWORD=654apekruA!@
      - DB_NAME=todolist
    command: ["sh","-c","sleep infinity"]
  mysql:
    image: mysql:8.0.26