version: "3.7"

networks:
  default:
    name: golang-learning
    external: true

services:
  golang:
    command: [ "sh","-c","sleep infinity" ]

  mysql:
    image: mysql:8.0.26

  php-consumer:
    build:
      context: .
      dockerfile: php/docker/php/Dockerfile
    container_name: php-consumer

  postgres:
    image: postgres:16
    container_name: postgres

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0

  kafka-ui-microservices:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-microservices